#include "level.h"
#include "entity_tile.h"
#include "tilemap.h"

#define DEFAULT_LEVEL_SIZE 10
#define DEFAULT_LEVEL_GRID_SIZE DEFAULT_LEVEL_SIZE * DEFAULT_LEVEL_SIZE

struct Tile default_grid[DEFAULT_LEVEL_GRID_SIZE] = 
{
    TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_NONE, TILE_SOLID,
    TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID, TILE_SOLID,
};

struct EntityCell default_entity_grid[DEFAULT_LEVEL_GRID_SIZE] =
{
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_KEY, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_PLAYER, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
       ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, ENTITY_NONE, 
};

struct Level get_default_level()
{
    struct Level level;
    level.tilemap = default_grid;
    level.entities = default_entity_grid;
    level.height = DEFAULT_LEVEL_SIZE;
    level.width = DEFAULT_LEVEL_SIZE;
    return level;
}

void render_level(struct Level level)
{
    vec2 pos = {0,0};
    float size = 1;
    render_tilemap(level.tilemap, level.width, level.height, pos, size);
    render_entities(level.entities, level.width, level.height, pos, size);
}
